id: P001664
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:13:19.491779
source_metadata:
  id: bdr:W3CN4690
  title: སྙིང་ཐིག་སྔོན་འགྲོའི་ཁྲིད་ཡིག་ཀུན་བཟང་བླ་མའི་ཞལ་ལུང་།
  author: ''
  volumes:
    9fcbe1722f694ff2aa148d16bc111598:
      image_group_id: I3CN4692
      title: ''
      volume_number: 1
      total_pages: 536
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
